### ISSUE TITLE
Port ekalappai to Linux 

### ISSUE THREAD

**Issue by mugunth** [thamizha/ekalappai#13]
To port eKalappai to linux, we need to find out the equivalent of these 2 microsoft windows functions in Iinux:

SetWindowsHookEx function
http://msdn.microsoft.com/en-us/library/windows/desktop/ms644990%28v=vs.85%29.aspx

PostMessage function
http://msdn.microsoft.com/en-us/library/windows/desktop/ms644944%28v=vs.85%29.aspx

We need to find either equivalent or similar functions in linux. These form the main feature of ekhook dll.
We may need to explore if ibus backend can be used for the above.

**Comment by manikk** [comment]
Unifying discussions in #23. Closing this issue for now.
