### ISSUE TITLE
Couldnt launch eKalappai - Artemis!9C3701008853 (Trojan)

### ISSUE THREAD

**Issue by mshariharan** [thamizha/ekalappai#19]
Hi, I have tried multiple times to install eKalappai 3.0.3, but McAfee quarantine the eKalappai.exe due to Artemis!9C3701008853 (Trojan).  But in McAfee site no information about this quarantine.

I tried uninstall, restart the system, install, but eKalappai.exe is not accessible.

I'm very interested to use tamil typewriter.
Appreciate your support.

**Comment by KaaSethu** [comment]
Dear mshariharan

Please follow this issue in issue#16 https://github.com/thamizha/ekalappai/issues/16

I will update that with what I found last week

Thanks

K. Sethu

**Comment by tamiliam** [comment]
மேலே கா. சேது சொன்னதுபோல் இச்சிக்கல்பற்றி நாம் வேறு இடத்தில் பேசுவதால், அதனை இங்கு மூடுகிறேன்.

**Comment by tamiliam** [comment]
கா. சேது சொன்னதுபோல் நாம் இச்சிக்கல்பற்றி வேறு இடத்தில் பேசுவதால், இதனை முடுகிறேன்.
